# Generated by Django 5.1.6 on 2025-03-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('C', 'C'), ('R', 'R'), ('M', 'M'), ('F', 'F'), ('E', 'E')], max_length=1)),
                ('room_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
