# Generated by Django 5.1.6 on 2025-03-03 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_room_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 3, 15, 16, 51, 821185, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
