# Generated by Django 5.1.6 on 2025-03-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
