# Generated by Django 5.1.6 on 2025-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_remove_feedback_email_remove_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'room_number')},
        ),
    ]
